---
title: 'Práctica 2 Visualización'
author: "Autor: Jordi Lladó valero"
date: "Junio 2021"
output:
  html_document:
    highlight: default
    number_sections: yes
    theme: cosmo
    toc: yes
    toc_depth: 2
    includes: 
      in_header: 
  word_document: default
  pdf_document:
    highlight: zenburn
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Se carga la libreria readxl para leer archivos xlsx
library(readxl)
#carga librería herramientas..
library(knitr)

```


```{r}
#Apertura del archivo xlsx
df<-read_xlsx("Education.xlsx")
attach(df)
colnames(df) <- c("Country_Name", "Country_Code", "Indicator_Name", "Indicator_Code", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969","1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979","1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989","1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020")
```



```{r}
#Se guardan las series temporales en distintas variables matrizes
Poblacion<-df[c(seq(1, 42768, by=162)),]
Govern1<-df[c(seq(16, 42768, by=162)),]
Govern2<-df[c(seq(17, 42768, by=162)),]
Expenditure<-df[c(seq(18, 42768, by=162)),]
Despesap<-df[c(seq(25, 42768, by=162)),]
staff<-df[c(seq(28, 42768, by=162)),]
School1<-df[c(seq(29, 42768, by=162)),]
School2<-df[c(seq(30, 42768, by=162)),]
School3<-df[c(seq(31, 42768, by=162)),]
Ratio<-df[c(seq(32, 42768, by=162)),]
Master1<-df[c(seq(36, 42768, by=162)),]
Master2<-df[c(seq(37, 42768, by=162)),]
Master3<-df[c(seq(38, 42768, by=162)),]
Doctor1<-df[c(seq(39, 42768, by=162)),]
Doctor2<-df[c(seq(40, 42768, by=162)),]
Doctor3<-df[c(seq(41, 42768, by=162)),]

```


```{r}
#Agrupación de atributos de interés en la variable o matriz final
final<-c(Poblacion[,1],Poblacion[,63],Govern1[,63], Govern2[,63],Expenditure[,63],Despesap[,63],staff[,63],School1[,63],School2[,63],School3[,63],Ratio[,63],Master1[,63],Master2[,63],Master3[,63],Doctor1[,63],Doctor2[,63],Doctor3[,63])

#Renombrar los distintos atributos
names(final)[1] <- "Country"
names(final)[2] <- "Población"
names(final)[3] <- "Gasto1 (%PIB)"
names(final)[4] <- "Gasto2 (%Gobierno)"
names(final)[5] <- "Gasto educación terciaria(% gasto público)"
names(final)[6] <- "Gasto total educación (% gasto público)"
names(final)[7] <- "Personal académico Educación terciaria (%mujer)"
names(final)[8] <- "Matrícula_terciaria(%hombres)"
names(final)[9] <- "Matrícula_tericaria(%mujeres)"
names(final)[10] <- "MAtrícula_terciaria"
names(final)[11] <- "Ratio" #"Pupil-teacher_ratio_tertiary"
names(final)[12] <- "Obtención_Master_total"
names(final)[13] <- "Obtención_Master_hombres"
names(final)[14] <- "Obtención_Master_mujeres" 
names(final)[15] <- "Obtención_Doctorado_Total" 
names(final)[16] <- "Obtención_doctorado_Hombres" 
names(final)[17] <- "Obtención_doctorado_Mujeres" 

```

```{r}
#Creación tabla archivo final
write.table(final, file = "final", append = FALSE, 
            quote = TRUE, sep = " ",
            eol = "\n", na = "NA", dec = ".", row.names = FALSE,
            col.names = TRUE, qmethod = c("escape"),
            fileEncoding = "")
```


